### ISSUE TITLE
Guides Guidelines

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#11]
### What's missing from the TRIP Guides

We need a simple overview of the basics of contributing new or material edits to Guides here.

### Expected content

Topics users might be interested in:

- The purpose of the guides
- Who can contribute to the guides
- What sort of contributions can be made to the guides
- How to contribute to the guides

### Actual content

Right now this is a stub page.

**Comment by hwhelchel** [comment]
@eugene-shvarts you had some good thoughts around some writing that needs care consideration of public perception. When you have a moment, share more about what you're thinking those guidelines should be here.

**Comment by eugene-shvarts** [comment]
@hwhelchel 
- Keep added material current, rather than future-facing
- Only make true statements consistent with our internal understanding of how our system works, and what is necessary and appropriate to inform the public about
- If unsure about language/topic/whether a feature is ready, ask the relevant people early and often. Otherwise it's all up to you

Those are the main ones on my mind, what do you think?

**Comment by hwhelchel** [comment]
@eugene-shvarts love these suggestions. @enki how does this look to you? 

If it looks good to Paul, Eugene would you be game to create a change request for this?

**Comment by hwhelchel** [comment]
- Organize guides around roles people can play on the network rather than around product or tech surfaces.
- If there is a section around a product or tech surface (e.g. The TRIP Report newsletter) structure it around how community members can contribute to that. If they can't contribute to it, remove or reorganize the section.

(In fact, maybe The TRIP Report section could be reworked into a role that people identify with instead.)

**Comment by hwhelchel** [comment]
More points to add to this guide:

- Avoid conjunctions
- Use second person
- Add list of naming conventions / word choices and reasoning
