### ISSUE TITLE
Android Users 

### ISSUE THREAD

**Issue by Stretch379** [TeleportXYZ/TRIP-Guides#69]
I am running into this problem, more and more with drivers in the DFW metroplex not being able to sign up because they use android phones due to the cost of the phone. 

It would be nice if we could get the android app going so they can at least get signed up even though the city is not unlocked. Or at least get something on the website stating about when it will be open.

**Comment by hwhelchel** [comment]
Hey Gary,

Thanks for your proposal.

Being on Android is important to us. It’s tough because as a startup we have to prioritize. 

Our next priority is getting the protocol rewards live and stress testing the mechanics of them. Android is a priority as well but will come after this other milestone has been achieved.

> Or at least get something on the website stating about when it will be open.

We have this section of the FAQ addressing this: https://guides.trip.dev/faq#is-the-app-available-on-android

What sort of changes to the Guides site are you proposing here? Editing that text or adding another section elsewhere?

**Comment by Stretch379** [comment]
Oh, OK. I did not realize that was there. I guess I haven’t paid too much attention to that side of it because I’m already logged in other than that just getting it ready is the only thing I had five people seem kind of upset yesterday over not being able to use their android. Sent from my iPhoneOn Mar 15, 2024, at 11:26 AM, Harry Whelchel ***@***.***> wrote:﻿
Hey Gary,
Thanks for your proposal.
Being on Android is important to us. It’s tough because as a startup we have to prioritize.
Our next priority is getting the protocol rewards live and stress testing the mechanics of them. Android is a priority as well but will come after this other milestone has been achieved.

Or at least get something on the website stating about when it will be open.

We have this section of the FAQ addressing this: https://guides.trip.dev/faq#is-the-app-available-on-android
What sort of changes to the Guides site are you proposing here? Editing that text or adding another section elsewhere?

**Comment by hwhelchel** [comment]
Are they upset because they are unable to refer people and earn rewards? 

Or are they upset because they cannot earn money by driving using the Android app?

If they are more upset because they are unable to refer people and earn rewards, there might be a way to allow them to get their own invite code to sign up people without the Android app. No promises, would need to research.

If they are upset because they cannot earn money by driving using the Android app, if the Android app existed they still would not be able to drive yet in DFW because DFW isn't live on the protocol.

**Comment by Stretch379** [comment]
It seems to be that they can’t sign up and that they are immediately going to a waitlist. I understand that they start won’t be able to drive. I think it’s the idea of being put on a waitlist that’s discouraging them.Sent from my iPhoneOn Mar 15, 2024, at 11:47 AM, Harry Whelchel ***@***.***> wrote:﻿
Are they upset because they are unable to refer people and earn rewards?
Or are they upset because they cannot earn money by driving using the Android app?
If they are more upset because they are unable to refer people and earn rewards, there might be a way to allow them to get their own invite code to sign up people without the Android app. No promises, would need to research.
If they are upset because they cannot earn money by driving using the Android app, if the Android app existed they still would not be able to drive yet in DFW because DFW isn't live on the protocol.

**Comment by hwhelchel** [comment]
Ok thank you for the feedback. Sharing this feedback with the team.

Since this issue tracker is for tracking proposals to the TRIP Guides site, I'm going to close this issue "as not planned" as no changes to the Guides site are planned based on this discussion.
