### ISSUE TITLE
Verifiers

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#7]
### What's missing from the TRIP Guides

We need a simple overview of the basics of Verifing with TRIP.

### Expected content

Topics verifiers might be interested in:

- How verifying works
- How verifiers make money
- How verifiers are different from operators

### Actual content

Right now this is a stub page.

**Comment by hwhelchel** [comment]
@Danie-Beukman fyi, thanks!

**Comment by hwhelchel** [comment]
@danie-beukman in terms of what I wrote above in the issue, don't look at that as specific instructions on what you should add here. Rather, I just wanted to model the format of an example issue for you to give you a framework to use when creating your own issues here.

As a first step, make a comment here on this issue as if you're creating a new issue and propose your changes. Then anyone on the team interested can join the discussion, get aligned, and then you can make your change request in GitBook.

Thanks!

**Comment by danie-beukman** [comment]
[This topic needs more consideration and clarity on what we're trying to achieve, and how we're trying to attract Verifiers. It's entirely plausible that initial Verifiers/Auditors will need to be approached and onboarded inorganically]

### **What is a Verifier?**

In order to comply with legal and regulatory requirements, maintain high safety standards, and ensure customer satisfaction, all rideshare network participants must undergo an authorization process appropriate for their role before being granted access to the network.

The TRIP Marketplace is democratically governed by network participants and holds ultimate authority on the network. Through voting on the TRIP Marketplace, the authority to make attestations can be temporarily and revocably delegated from the TRIP marketplace to dedicated [Compliance Auditors](https://guides.trip.dev/other-roles/auditors) and Verifiers.

A Verifier is a service or entity that validates claims or assertions made by users or entities within the decentralized ecosystem. Verifiers play a crucial role in establishing trust and credibility when traditional centralized authorities are not present. Verifiers inspect driver licenses, perform car inspections, conduct background checks, verify phone numbers, and take other actions necessary to ensure the legitimacy of all network participants.

### **What are the requirements to become a Verifier?**
Verifiers must be in legal and operational compliance with all applicable regulations and laws before they begin providing attestation services to the network.

[Need to have more content here on the legal requirements - do we want them to be lawfirms/legally qualified? Admission to State bar? 

### **What responsibilities does a Verifier have?**
[Needs to be fleshed out - what happens if a Verifier verifies someone incorrectly? Do they need insurance?]

### **How do I become a Verifier?**
If you or your firm would like to be considered as a Verifier for The Rideshare Protocol, [reach out to us](mailto:verifier@dec.dev). 

To ensure that Verifiers are compliant with local regulation and operational requirements, the TRIP Marketplace votes to deputize dedicated compliance auditing firms. These firms receive authorization by multi-sig keys to sign off on the regulatory and operational readiness of Operators and Verifiers.

**Comment by hwhelchel** [comment]
@danie-beukman this looks great thank you. 

> Compliance Auditors

What do you think of simplifying the name of this role to "Auditors"?

> service or entity that validates claims or assertions made by users or entities

Not a blocker, that said, would be easier to follow if we picked out one word for each of these phrases and didn't have the "or" conjunctions.

> [Need to have more content here on the legal requirements - do we want them to be lawfirms/legally qualified? Admission to State bar?]

These sidebars you include are great. When you feel a sidebar like that needs to be raised, that's a great sign that a new issue should be created here in GitHub to organize discussion around that question. Let's not include these sidebars in the GitBook guides for now. Any sections you have above that are not filled in and are just sidebars can be left out for later contributors to add.

> you or your firm

Same suggestion about "or" conjunctions. 

> [reach out to us](mailto:verifier@dec.dev).

What about, "reach out to the DEC team" or "reach out to the TRIP core team" (TRIP core team being us)? 

"Us" to me would make more sense if this document was a one way support document from us as a company to the community as users. By calling out "DEC team" or "TRIP core team" instead we don't "other" the community members by not including them in "us".

None of these are blockers. All in all, looks great to me to create a change request in GitBook if you haven't yet.

**Comment by hwhelchel** [comment]
P.S. I'm getting a ton of value out using this tool to help me level up my writing: https://hemingwayapp.com/

**Comment by hwhelchel** [comment]
> > Compliance Auditors
> 
> What do you think of simplifying the name of this role to "Auditors"?

Thinking out loud, this should be a separate issue and edited across the board if we make this change. So let's hold on this local edit for now.

**Comment by hwhelchel** [comment]
Addressed issue here: https://github.com/TeleportXYZ/TRIP-Guides/pull/30

**Comment by hwhelchel** [comment]
@danie-beukman nice work with #6 I just merged it. Please submit a change request for this page when you have a moment.

**Comment by hwhelchel** [comment]
v1 shipped https://guides.trip.dev/other-roles/verifiers

edits welcomed
